### ISSUE TITLE
App crashes as you click on the "Scrape" button. (TextView does not update)

### ISSUE THREAD

**Issue by DevRomu** [DevRomu/basic_Web_Scrape#3]
The app crashes as you click on the app button, it could either be an issue with the way we are fetching the web scrape or it's a performance issue with the app.

**Comment by CCianfloneDev** [comment]
If you enter debugger mode and step into the code you will see at the .Connect line it throws an exception in Looper.Java where observer != null and it throws this exception: android.os.NetworkOnMainThreadException.

Here is ChatGPT's answer to the error:
The android.os.NetworkOnMainThreadException is thrown when you attempt to perform network operations on the main UI thread in Android. This is a safety measure to prevent network operations from blocking the UI and making the app unresponsive. To fix this issue, you should perform network operations, such as connecting to a URL, in a background thread, such as using AsyncTask, Kotlin Coroutines, or a separate thread.

I have a working copy that pulls from the API and displays the text. You do need to change the textview to allow scrolling because you can't see all the quotes.

**Comment by DevRomu** [comment]
> If you enter debugger mode and step into the code you will see at the .Connect line it throws an exception in Looper.Java where observer != null and it throws this exception: android.os.NetworkOnMainThreadException.
> 
> Here is ChatGPT's answer to the error: The android.os.NetworkOnMainThreadException is thrown when you attempt to perform network operations on the main UI thread in Android. This is a safety measure to prevent network operations from blocking the UI and making the app unresponsive. To fix this issue, you should perform network operations, such as connecting to a URL, in a background thread, such as using AsyncTask, Kotlin Coroutines, or a separate thread.
> 
> I have a working copy that pulls from the API and displays the text. You do need to change the textview to allow scrolling because you can't see all the quotes.

I'll probably keep the quote to five or four for the sake of  performance, but also readability. Thanks for the suggestions Cole.

**Comment by CCianfloneDev** [comment]
Fixed :)
